export const gridSpacing = 3;
export const drawerWidth = 260;
export const poundSymbol = "£ ";

export const testModuleAr = [
  "RT02: Crawler crane | 15 minutes",
  "RT04: Tower crane | 15 minutes",
  "RT05: Dragline | 15 minutes",
  "RT06: Truck mounted boom concrete pump | 15 minutes",
  "RT09: Forward tipping dumper | 15 minutes",
  "RT12: Excavator 180 | 15 minutes",
  "RT14: Masted forklift truck | 15 minutes",
  "RT17: Telescopic handler | 15 minutes",
  "RT19: Grader | 15 minutes",
  "RT20: Hoist | 15 minutes",
  "RT21: Wheeled loading shovel | 15 minutes",
  "RT22: Tracked loading shovel | 15 minutes",
  "RT23: Skid steer loader | 15 minutes",
  "RT24: Motorised scraper | 15 minutes",
  "RT25: MEWP - scissor | 15 minutes",
  "RT26: MEWP - boom | 15 minutes",
  "RT27: MEWP - mast climber | 15 minutes",
  "RT30: Piling rig - tripod | 15 minutes",
  "RT31: Ride on roller | 15 minutes",
  "RT32: Soil/landfill compactor | 15 minutes",
  "RT33: Agricultural tractor | 15 minutes",
  "RT34: Crawler - tractor/dozer | 15 minutes",
  "RT35: Crawler - tractor/side boom | 15 minutes",
  "RT36: Lorry loader | 15 minutes",
  "RT37: Trencher | 15 minutes",
  "RT39: Skip handler | 15 minutes",
  "RT40: Slinger/signaller | 15 minutes",
  "RT41: Loader-compressor | 15 minutes",
  "RT42: Crusher | 15 minutes",
  "RT43: Screener | 15 minutes",
  "RT44: Trailer mounted concrete pump | 15 minutes",
  "RT45: Piling rigs | 15 minutes",
  "RT49: Loader/securer non STGO | 15 minutes",
  "RT50: Loader/securer STGO | 15 minutes",
  "RT56: Dump trucks | 15 minutes",
  "RT59: Excavator 360 | 15 minutes",
  "RT60: Mobile crane | 15 minutes",
  "RT61: Appointed person | 15 minutes",
  "RT62: Crane/lifting operations supervisor | 15 minutes",
  "RT63: Pedestrian operated tower crane | 15 minutes",
  "RT65: Demolition plant | 15 minutes",
  "RT66: Compact crane | 15 minutes",
];

export const testVoiceOver = [
  "none",
  "English",
  "Welsh",
  "German",
  "Lithuanian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Bulgarian",
  "Czech",
  "Hungarian",
  "French",
  "Spanish",
];

export const payStatus = [
  "Payment Not Initiated",
  "Payment Pending",
  "Paid",
  "Failed",
  "Payment initiated but failed",
  "Refunded",
  "Follow Up",
];
export const payStatusColor = [
  "default",
  "warning",
  "success",
  "error",
  "warning",
  "warning",
  "warning",
];

export const orderCheckPointAr = [
  "Details Capture Complete",
  "Details Capture Incomplete",
  "Documents Pending",
  "Order Placed.",
  "Confirmation Sent",
  "Application Under Process",
  "Order Complete",
  "Refunded",
  "Follow Up",
];
